<?xml version="1.0"?>
<package format="2">
  <name>lr30_project11</name>
  <version>0.0.0</version>
  <description>Launch and config for use with Chance LR30 USV</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>depthai_marine</depend>
  <depend>rclcpp</depend>
  <exec_depend>cube_bathymetry</exec_depend>
  <exec_depend>marine_ais_tools</exec_depend>
  <exec_depend>nmea_navsat_driver</exec_depend>
  <exec_depend>marine_autonomy</exec_depend>
  <depend>joint_state_publisher</depend>
  <depend>robot_state_publisher</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
