/**/platform_sender:
  ros__parameters:
    width: 2.0
    length: 9.144
    color:
      red: 1.0
      green: 0.8
      blue: 0.1

    nav:
      source_names:
        - sbg
      sources:
        sbg:
          topics:
            orientation: "navigation/sbg/orientation"
            position: "navigation/sbg/fix"
            velocity: "navigation/sbg/vel"

/**/cube_bathymetry:
  ros__parameters:
    cell_size: 1.5
    grid_cell_count: 25

/**/detections_to_pointcloud:
  ros__parameters:
    minimum_range: 5.0
    maximum_range: 100.0
    sensor_names:
      - sbg
    sensors:
      sbg:
        topics:
          orientation: "orientation"
          position: "position"
          velocity: "velocity"

/**/manda_coverage:
  ros__parameters:
    soundings_topic: "sensors/sonar/soundings"
    display_topic: "manda_coverage_display"

/**/mru_transform:
  ros__parameters:
    sensors:
      sbg:
        topics:
          orientation: "navigation/sbg/orientation"
          position: "navigation/sbg/fix"
          velocity: "navigation/sbg/vel"
    sensor_names:
    - sbg

/**/udp_bridge:
  ros__parameters:
    name: lr30
    maximum_packet_size: 1200
    remotes_list:
    - operator
    remotes:
      operator:
        connections_list:
        - default
        connections:
          default:
            host: deadpooldz
            port: 4200
            maximum_bytes_per_second: 1500000
            topics_list:
            - camera_left
            - camera_left_info
            - camera_left_raw
            - camera_right
            - camera_right_info
            - camera_right_raw
            - camera_ewasr_left
            - camera_ewasr_left_info
            - camera_ewasr_left_raw
            - camera_ewasr_right
            - camera_ewasr_right_info
            - camera_ewasr_right_raw
            - camera_jolo_left
            - camera_jolo_right
            - position
            - heading
            - velocity
            - platforms
            - soundings
            - tf
            - manda_coverage_display
            - command_response
            - mission_status
            topics:
              camera_left: {source: sensors/cameras/left/image_raw/compressed, period: 1.0}
              camera_left_info: {source: sensors/cameras/left/camera_info}
              camera_left_raw: {source: sensors/cameras/left/image_raw, period: -1.0}
              camera_right: {source: sensors/cameras/right/image_raw/compressed, period: 1.0}
              camera_right_info: {source: sensors/cameras/right/camera_info}
              camera_right_raw: {source: sensors/cameras/right/image_raw, period: -1.0}
              position: {source: navigation/sbg/fix}
              heading: {source: navigation/sbg/orientation}
              velocity: {source: navigation/sbg/vel}
              platforms: {source: /project11/platforms}
              soundings: {source: sensors/sonar/soundings}
              tf: {source: /tf}
              manda_coverage_display: {source: manda_coverage_display}
              command_response: {source: project11/response}
              camera_ewasr_left: {source: sensors/cameras/left/ewasr/compressed}
              camera_ewasr_left_info: {source: sensors/cameras/left/ewasr/camera_info}
              camera_ewasr_left_raw: {source: sensors/cameras/left/ewasr, period: -1.0}
              camera_ewasr_right: {source: sensors/cameras/right/ewasr/compressed}
              camera_ewasr_right_info: {source: sensors/cameras/right/ewasr/camera_info}
              camera_ewasr_right_raw: {source: sensors/cameras/right/ewasr, period: -1.0}
              camera_jolo_left: {source: sensors/cameras/left/jolo}
              camera_jolo_right: {source: sensors/cameras/right/jolo}
              mission_status: {source: project11/status/mission_manager}
