/**/platform_sender:
  ros__parameters:
    width: 2.0
    length: 9.144
    color:
      red: 1.0
      green: 0.8
      blue: 0.1

    nav:
      source_names:
        - sbg
      sources:
        sbg:
          topics:
            orientation: "navigation/sbg/orientation"
            position: "navigation/sbg/fix"
            velocity: "navigation/sbg/vel"


/**/mru_transform:
  ros__parameters:
    sensors:
      sbg:
        topics:
          orientation: "navigation/sbg/orientation"
          position: "navigation/sbg/fix"
          velocity: "navigation/sbg/vel"
    sensor_names:
    - sbg


/**/udp_bridge:
  ros__parameters:
    name: lr30
    maximum_packet_size: 1400
    remotes_list:
    - operator
    remotes:
      operator:
        connections_list:
        - default
        connections:
          default:
            host: deadpooldz
            port: 4200
            maximum_bytes_per_second: 1500000
            topics_list:
            - position
            - heading
            - velocity
            - platforms
            - robot_description
            - tf
            topics:
              position: {source: navigation/sbg/fix}
              heading: {source: navigation/sbg/orientation}
              velocity: {source: navigation/sbg/vel}
              platforms: {source: /project11/platforms}
              robot_description: {source: robot_description}
              tf: {source: /tf}

